### PR TITLE
Add py3 version of snakefood

### PR DESCRIPTION
**Pull request by sebastian-luna-valero**

### CODE REVIEW

**Comment by sebastian-luna-valero** [comment]
Hi @pmlandwehr @conda-forge-coordinator 

I am trying to use `2to3` to package `snakefood` for Py3.

I am getting `PermissionError: [Errno 13] Permission denied: '/feedstock_root/build_artefacts'` in `circleci`.

Any suggestions?

Best regards,
Sebastian

**Comment by sebastian-luna-valero** [comment]
@conda-forge-admin, please rerender

**Comment by pmlandwehr** [comment]
Have you run any tests (ideally, those provided by `snakefood`) after using `2to3`? e.g. I'm seeing [this  thread](https://bitbucket.org/blais/snakefood/issues/3/python-3-support#comment-43966467) which seems to imply that `2to3` doesn't handle all of the necessary changes. We don't need the full test suite in conda-forge, obviously, but we should check against it before providing something not covered by the original package...

**Comment by sebastian-luna-valero** [comment]
I am running the tests that were already part of the `meta.yaml`:
https://github.com/conda-forge/snakefood-feedstock/blob/master/recipe/meta.yaml#L28

Hopefully that will suffice?

**Comment by pmlandwehr** [comment]
> Hopefully that will suffice?

I don't really think so in this case? `meta.yaml` just does basic imports; it doesn't run any parts of `snakefood`'s test suite. (If the imports fail, something is really broken.) Can you build locally with `2to3` and then try running the tests included with source?

**Comment by sebastian-luna-valero** [comment]
You are right @pmlandwehr 

If I use Maik Riechert's patches, `import snakefood.fallback` does not work.

If I use the latest release from bitbucket, the code still depends on the `compiler` module which is Py2 only. I don't get why since I though Martin Blais would have merged Maik's changes into the master branch:
https://bitbucket.org/blais/snakefood/commits/branch/default

Any ideas?

**Comment by pmlandwehr** [comment]
You can bundle `.patch` files into the recipe and ask that they be applied before building the recipe -I'd say try using those from the unmerged branch to make the changes here, before the recipe is built.

**Comment by roachsinai** [comment]
Hi, @sebastian-luna-valero thanks for you work. But could you please provide a PYPI package?

**Pull request closed without merging**
